apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: acft6iars-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jsmid/rhtap-qe-jsmid:0fb020b5244d83725799130ce42caa64eb320293@sha256:e54a6b0af7396e19b767aac565965b7eb2283a1737947e1a93176c17b9e11873
          name: container-image
